# Generated by Django 3.0.3 on 2020-02-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20200215_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='voted',
            name='voted_item',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
